spring.application.name=assignment4
spring.mvc.view.suffix=.html
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.url=jdbc:h2:tcp://localhost/~/test
spring.h2.console.enabled=true